spring:
 main:
  allow-bean-definition-overriding: true

infinispan:
  embedded:
    enabled: true
  client:
   hotrod:
    server_list: localhost:1122
    client_intelligence: BASIC
    auth_realm: default
    auth_username: admin
    auth_password: admin
    use_auth: true

#infinispan.client.hotrod.sasl_mechanism=DIGEST-MD5