server:
  port: 8080
logging:
  level:
    root: error
    org.apache.kafka.clients: info

spring:
  application:
    name: spring-kafka-producer
  kafka:
    bootstrap-servers: 192.168.25.53:9092,192.168.25.53:9192,192.168.25.53:9292
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
    properties:
      spring:
        json:
          trusted:
            packages: 'org.examples.*'
