logging:
  level:
    root: warn
    org.springframework.jdbc: debug

spring:
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:tcp://localhost:9092/~/test
    url: jdbc:h2:mem:test
    username: sa
    password: sa
    hikari:
      connection-timeout: 10000
  sql:
    init:
      schema-locations:  optional:classpath:schema.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      'org.hibernate.envers.default_schema': LOG