logging:
  level:
    root: info
    org.examples: debug

spring:
  application:
    name: logging-response-time
  datasource:
    url: jdbc:postgresql://192.168.11.131:5432/test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
