spring:
  application:
    name: async-web-application
  boot:
    admin:
      client:
        url: http://localhost:9099
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true