server:
  port: 8080
logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  elastic:
    metrics:
      export:
        enabled: on