logging:
  level:
    org.springframework: info
    org.springframework.cloud.gateway.route: info

spring:
 application:
   name: spring-boot-admin

eureka:
  client:
    enabled: false
server:
  port: 9099
